#!/usr/bin/env bash

if [ "$#" -ne 2 ]; then
    cat << EOF
Usage: ./push "VERSION" "MESSAGE"
Examples:
./push "1.0.0" "Big features"
latest version: 
EOF
    cat version
    exit
fi


VERSION="$1"
MESSAGE="$2"
echo $VERSION > version
git add .
git commit -m "add : $MESSAGE"
git push