version: 2.0

jobs:
  build:
    docker:
      - image: thomasweise/texlive
    steps:
      - checkout
      - run:
          name: Compile
          command: make
      - run:
          name: Move artifacts
          command: |
            mkdir -p results
            mv examples/cv.pdf results
            mv examples/resume.pdf results
            mv examples/coverletter.pdf results
      - run:
          name: List Dir
          command: |
            pwd
            ls -la
      - persist_to_workspace:
          root: .
          paths: 
            - results/
      - run:
          name: List Dir
          command: |
            pwd
            ls -la
  deploy:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - attach_workspace:
          at: ./results
      - run:
          name: List Dir
          command: |
            pwd
            ls -la
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=$(cat version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./results
workflows:
  version: 2
  main-workflow:
    jobs:
      - build
      - deploy:
          requires:
            - build