version: 2.0

jobs:
  build:
    docker:
      - image: thomasweise/texlive
    steps:
      - checkout
      - run:
          name: Compile
          command: make
      - run:
          name: Move artifacts
          command: |
            mkdir -p results
            mv examples/cv.pdf results
            mv examples/resume.pdf results
            mv examples/coverletter.pdf results
      - store_artifacts:
          path: ./results
  deploy:
    docker:
      - image: cibuilds/github:0.13
    steps:
      - checkout
      - attach_workspace:
          at: ./results
      - run:
          name: "Publish Release on GitHub"
          command: |
            echo "${CIRCLE_TAG}"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./results/
workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build